# Installs nginx 1.20 (alpine) from dockerhub
FROM nginx:1.20-alpine

# Replaces nginx.conf file
RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/
# Replaces nginx's conf.d file
RUN rm /etc/nginx/conf.d/default.conf
COPY portfolio_website.conf /etc/nginx/conf.d/